Update tianqi.yml

diff --git a/.github/workflows/tianqi.yml b/.github/workflows/tianqi.yml
--- a/.github/workflows/tianqi.yml
+++ b/.github/workflows/tianqi.yml
@@ -20,6 +20,23 @@ jobs:
         git config --global user.email "actions@github.com"
         git config --global user.name "GitHub Actions"
 
+    - name: Delete tq.txt File
+      run: |
+        if [ -f "php/tq.txt" ]; then
+          rm -rf php/tq.txt
+          git rm -r --cached php/tq.txt
+          git commit -m "Delete tq.txt" || echo "No changes to commit"
+          git push
+        else
+          echo "tq.txt not found, skipping deletion"
+      env:
+        PAT: ${{ secrets.GITHUB_TOKEN }}
+    
+    - name: Create php directory and tq.txt
+      run: |
+        mkdir -p php
+        touch php/tq.txt
+
     - name: Set up PHP
       uses: shivammathur/setup-php@v2
       with:
